# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docmanfu < Formula
  desc "Watch a directory and auto-upload new files to a DocManFu instance"
  homepage "https://github.com/DocManFu/DocManFu"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DocManFu/DocManFu/releases/download/v1.0.0/docmanfu_darwin_amd64.tar.gz"
      sha256 "39f12915043f3b93c650db4a668dd23c185505ca080b033841ef6d8344ced130"

      define_method(:install) do
        bin.install "docmanfu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DocManFu/DocManFu/releases/download/v1.0.0/docmanfu_darwin_arm64.tar.gz"
      sha256 "de6efe117dc249d0183869c07826ebd528b26676656fceb1f25553266bdd5181"

      define_method(:install) do
        bin.install "docmanfu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DocManFu/DocManFu/releases/download/v1.0.0/docmanfu_linux_amd64.tar.gz"
      sha256 "354e2830ac8515b18e77696edb0872ac5c49d4fa3baaeca59b3e1e71190e19f8"
      define_method(:install) do
        bin.install "docmanfu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DocManFu/DocManFu/releases/download/v1.0.0/docmanfu_linux_arm64.tar.gz"
      sha256 "284e12c6df5786e9610b6621851b924276d864b258ae89636d81d6ad2b6f8676"
      define_method(:install) do
        bin.install "docmanfu"
      end
    end
  end

  test do
    system "#{bin}/docmanfu", "--help"
  end
end
